Repository Exawind/nalu-wind, pull requests merged in 2021-03, with the labels that each got.

#783 Add FLLC to NGP actuator models
  .gitignore
  include/Realm.h
  include/actuator/ActuatorBladeDistributor.h
  include/actuator/ActuatorBulk.h
  include/actuator/ActuatorBulkFAST.h
  include/actuator/ActuatorBulkSimple.h
  include/actuator/ActuatorExecutor.h
  include/actuator/ActuatorExecutorsFASTNgp.h
  include/actuator/ActuatorExecutorsSimpleNgp.h
  include/actuator/ActuatorFLLC.h
  include/actuator/ActuatorFunctorsFAST.h
  include/actuator/ActuatorModel.h
  include/actuator/ActuatorParsing.h
  include/actuator/ActuatorScalingFLLC.h
  include/actuator/ActuatorTypes.h
  reg_tests/CTestList.cmake
  reg_tests/test_files/ActLineSimpleFLLC/ActLineSimpleFLLC.yaml
  reg_tests/test_files/nrel5MWactuatorLineFllc/nrel5MWactuatorLineFllc.yaml
  src/LowMachEquationSystem.C
  src/Realm.C
  src/actuator/ActuatorBladeDistributor.C
  src/actuator/ActuatorBulk.C
  src/actuator/ActuatorBulkFAST.C
  src/actuator/ActuatorBulkSimple.C
  src/actuator/ActuatorExecutor.C
  src/actuator/ActuatorExecutorsFASTNgp.C
  src/actuator/ActuatorExecutorsSimpleNgp.C
  src/actuator/ActuatorFLLC.C
  src/actuator/ActuatorFunctorsFAST.C
  src/actuator/ActuatorFunctorsSimple.C
  src/actuator/ActuatorModel.C
  src/actuator/ActuatorParsing.C
  src/actuator/ActuatorParsingFAST.C
  src/actuator/ActuatorParsingSimple.C
  src/actuator/CMakeLists.txt
  unit_tests/actuator/CMakeLists.txt
  unit_tests/actuator/UnitTestActuatorBladeDistributor.C
  unit_tests/actuator/UnitTestActuatorFLLC.C
  unit_tests/actuator/UnitTestActuatorFunctors.C
  unit_tests/actuator/UnitTestActuatorParsing.C
  unit_tests/actuator/UnitTestActuatorParsingFAST.C
  unit_tests/actuator/UnitTestActuatorSearch.C
Labels: enhancement

#820 Fix memory leak in TKE EQS
  src/TurbKineticEnergyEquationSystem.C
Labels: bug

#822 Fix for actLineSimple reg test
  src/actuator/ActuatorBladeDistributor.C
  src/actuator/ActuatorParsing.C
  unit_tests/actuator/UnitTestActuatorBladeDistributor.C
  unit_tests/actuator/UnitTestActuatorFunctors.C
Labels: bug

#833 Fix bug in NGP loops unit tests for edges
  unit_tests/ngp_kernels/UnitTestNgpLoops.C
Labels: bug, failing-tests

#834 Remove element scheme logic from ABLTopBC interface
  src/LowMachEquationSystem.C
Labels: bug, failing-tests
